### ISSUE TITLE
レビュー

### ISSUE THREAD

**Issue by tkym61** [morrr/Dragbox#24]
■設定画面
　　-DROPBOXの表記だと一瞬何の製品か分からない。「Dropbox」じゃないと違和感あります。。
　　-ユーザ　の項目がテキストボックスに見える。　
　　(リンクボタンが下にあるので、こちらにアドレスを入力してリンクする？と思いました。) 　　
　　-認証後はフォルダ選択画面へ直接遷移しても良いかと思います。
　　-説明がないとキャッシュ削除の必要性が分からない。

■フォルダ選択画面
　　-先に移動先フォルダを選択する必要があることが分かりにくい
　　-削除時に確認アラートが欲しい。
　　(画像削除時はアラート無しの方が効率的で良いかと思いますが、フォルダごと間違って消してしまうのは怖いです)
　　-フォルダのアイコンが画像アイコンに見える(フォルダだと分からない)
　　-既存フォルダとフォルダ作成のアイコンが似ているので分かりにくい。
　　　フォルダ作成アイコンの色を変えるなど一目でわかるアイコンが良い
　　-選択済フォルダの長押しで表示される▲三角のアイコンの動作が不明です。
　　-ルートフォルダが / 表記だと分からない

■画像選択画面
　　-横長の画像を選択した場合にどのフォルダに入るかが分かりにくい
　　　遷移先のフォルダにエフェクトなど追加すれば分かりやすいのでは
　　-画像の比が原寸画像のままドラッグするので操作しにくい(縦パノラマ画像/横パノラマ画像など特に)
　　-隣接する画像のみでも良いので複数選択が出来ると便利かと

■総評
　　-大量の画像を１つ１つ確認しながら効率良く移動させるには良いと思います。
　　フォルダ振り分けが簡単に素早く出来ている実感はありました。
　　その分１つ１つの動作でちょっとしたラグなどがあると通常以上に気になった印象です。

　　また、ファイルの削除が簡単に出来るのは長所だと思った反面、間違えて消してしまいそうだとも思いました。可能なら復元などあると安心かもしれません。

**Comment by morrr** [comment]
レビューありがとうございます。

>-DROPBOXの表記だと一瞬何の製品か分からない。「Dropbox」じゃないと違和感あります。。

#37 フォントの変更により対応可能です。が軽微なため対応保留します。

>-ユーザ　の項目がテキストボックスに見える。　
>(リンクボタンが下にあるので、こちらにアドレスを入力してリンクする？と思いました。) 　　

#38, #39 該当のセルをタップしてもリンクができるように対応します。

>-認証後はフォルダ選択画面へ直接遷移しても良いかと思います。

#40 そのように対応します。

>-説明がないとキャッシュ削除の必要性が分からない。

#41 説明文を追加して対応します。

**Comment by morrr** [comment]
>-先に移動先フォルダを選択する必要があることが分かりにくい

iTunes Store公開時のスクリーンショットで、操作を説明する予定です。
また画面下側に表示される文言を修正します(#42)

>-削除時に確認アラートが欲しい。
>(画像削除時はアラート無しの方が効率的で良いかと思いますが、フォルダごと間違って消してしまうのは怖いです)

アラートを表示させるように修正します(#16)

>-フォルダのアイコンが画像アイコンに見える(フォルダだと分からない)
>-既存フォルダとフォルダ作成のアイコンが似ているので分かりにくい。
>フォルダ作成アイコンの色を変えるなど一目でわかるアイコンが良い

アイコンを差し替えて対応します(#43)

>-選択済フォルダの長押しで表示される▲三角のアイコンの動作が不明です。

移動先フォルダに遷移するためのボタンですが、現在不具合により機能していません。
一時的に非表示にして対応します(#30)

>-ルートフォルダが / 表記だと分からない

適切な表示が不明なため、対応保留します(#44)
こう表示したらルートだとわかる、などありましたら教えて下さい。

**Comment by morrr** [comment]
>-横長の画像を選択した場合にどのフォルダに入るかが分かりにくい
>遷移先のフォルダにエフェクトなど追加すれば分かりやすいのでは

時間を要するため保留します(#12)

>-画像の比が原寸画像のままドラッグするので操作しにくい(縦パノラマ画像/横パノラマ画像など特に)

表示される大きさを制限するよう対応します(#45)

>-隣接する画像のみでも良いので複数選択が出来ると便利かと

UIの大幅な変更が必要なため保留します(#46)
