### ISSUE TITLE
レビュー時不具合

### ISSUE THREAD

**Issue by tkym61** [morrr/Dragbox#25]
■共通
　-wi-fi下で検証しましたが容量の大きな画像のドラッグ時に動作が止まることが多々ありました。

■フォルダ選択画面
　　-既存フォルダと同じファイル名を追加すると何も追加されない。確認アラートか何か必要かと思います。
　　-ルートフォルダを移動先フォルダリストから削除すると再起動までルートフォルダへの移動が不可

■画像選択画面
　　-画像読み込みが完了しない状態(サムネイルがボケている状態)でフォルダへ移動させていたら落ちました。

**Comment by morrr** [comment]
不具合出しありがとうございます。

>-wi-fi下で検証しましたが容量の大きな画像のドラッグ時に動作が止まることが多々ありました。
>-既存フォルダと同じファイル名を追加すると何も追加されない。確認アラートか何か必要かと思います。
>-画像読み込みが完了しない状態(サムネイルがボケている状態)でフォルダへ移動させていたら落ちました。

#33, #34, #36 今バージョンで対応します。


>-ルートフォルダを移動先フォルダリストから削除すると再起動までルートフォルダへの移動が不可

#35 対応に時間を要するため、次バージョンに保留します。
